import type { Event, TeamMember, GalleryAlbum } from './types';

export const mockEvents: Event[] = [
  {
    id: '1',
    title: 'AI & Machine Learning Workshop',
    date: '2024-08-15',
    category: 'Workshop',
    description: 'An intensive workshop covering the fundamentals of AI and Machine Learning with hands-on sessions.',
    imageUrl: 'https://picsum.photos/seed/3/400/250',
    imageHint: 'AI workshop',
    status: 'upcoming',
  },
  {
    id: '2',
    title: 'Intro to Blockchain Seminar',
    date: '2024-09-02',
    category: 'Seminar',
    description: 'Discover the world of blockchain technology and its applications beyond cryptocurrencies.',
    imageUrl: 'https://picsum.photos/seed/4/400/250',
    imageHint: 'blockchain seminar',
    status: 'upcoming',
  },
  {
    id: '3',
    title: 'CodeSprint 2024',
    date: '2024-09-20',
    category: 'Competition',
    description: 'Annual flagship coding competition. Compete with the best and win exciting prizes.',
    imageUrl: 'https://picsum.photos/seed/5/400/250',
    imageHint: 'coding competition',
    status: 'upcoming',
  },
  {
    id: '4',
    title: 'Cybersecurity Essentials Webinar',
    date: '2024-10-05',
    category: 'Webinar',
    description: 'Learn about the essential practices to stay safe in the digital world from industry experts.',
    imageUrl: 'https://picsum.photos/seed/6/400/250',
    imageHint: 'cybersecurity webinar',
    status: 'upcoming',
  },
  {
    id: '5',
    title: 'Robotics & Automation Fair',
    date: '2024-04-22',
    category: 'Workshop',
    description: 'A look back at our successful event showcasing student-built robots and automation projects.',
    imageUrl: 'https://picsum.photos/seed/7/400/250',
    imageHint: 'robotics workshop',
    status: 'past',
  },
  {
    id: '6',
    title: 'The Future of IoT',
    date: '2024-03-10',
    category: 'Seminar',
    description: 'Experts discussed the future trends and impact of the Internet of Things on our daily lives.',
    imageUrl: 'https://picsum.photos/seed/8/400/250',
    imageHint: 'IoT seminar',
    status: 'past',
  },
];

export const mockTeam: TeamMember[] = [
  {
    id: '1',
    name: 'Priya Sharma',
    role: 'Chairperson',
    bio: 'Leads the student branch with a vision for innovation and collaboration. Passionate about empowering students.',
    imageUrl: 'https://picsum.photos/seed/15/400/400',
    imageHint: 'professional headshot',
    linkedin: '#',
    github: '#',
  },
  {
    id: '2',
    name: 'Rahul Verma',
    role: 'Vice Chairperson',
    bio: 'Assists in managing branch activities and focuses on strategic growth and member engagement.',
    imageUrl: 'https://picsum.photos/seed/16/400/400',
    imageHint: 'professional headshot',
    linkedin: '#',
  },
  {
    id: '3',
    name: 'Anika Singh',
    role: 'Secretary',
    bio: 'Manages all documentation, communications, and organizational tasks for the student branch.',
    imageUrl: 'https://picsum.photos/seed/17/400/400',
    imageHint: 'professional headshot',
    linkedin: '#',
    github: '#',
  },
  {
    id: '4',
    name: 'Sameer Khan',
    role: 'Treasurer',
    bio: 'Oversees the financial health of the branch, managing budgets for events and activities.',
    imageUrl: 'https://picsum.photos/seed/18/400/400',
    imageHint: 'professional headshot',
    linkedin: '#',
  },
  {
    id: '5',
    name: 'Neha Gupta',
    role: 'Events Head',
    bio: 'The creative mind behind all our engaging workshops, seminars, and competitions.',
    imageUrl: 'https://picsum.photos/seed/19/400/400',
    imageHint: 'professional headshot',
    linkedin: '#',
    github: '#',
  },
  {
    id: '6',
    name: 'Vikram Reddy',
    role: 'Technical Head',
    bio: 'Leads the technical projects and workshops, mentoring students in various tech domains.',
    imageUrl: 'https://picsum.photos/seed/20/400/400',
    imageHint: 'professional headshot',
    linkedin: '#',
    github: '#',
  },
  {
    id: '7',
    name: 'Meera Desai',
    role: 'Marketing Head',
    bio: 'Spreads the word about our activities and manages our social media presence.',
    imageUrl: 'https://picsum.photos/seed/21/400/400',
    imageHint: 'professional headshot',
    linkedin: '#',
  },
  {
    id: '8',
    name: 'Arjun Mehta',
    role: 'Membership Chair',
    bio: 'Focuses on growing our community and ensuring members get the most out of their experience.',
    imageUrl: 'https://picsum.photos/seed/22/400/400',
    imageHint: 'professional headshot',
    linkedin: '#',
  },
];

export const mockGallery: GalleryAlbum[] = [
  {
    id: '1',
    title: 'Tech Fest 2023',
    category: 'Festivals',
    imageUrl: 'https://picsum.photos/seed/9/400/300',
    imageHint: 'tech festival',
    imageCount: 45,
  },
  {
    id: '2',
    title: 'AI Workshop',
    category: 'Workshops',
    imageUrl: 'https://picsum.photos/seed/10/400/300',
    imageHint: 'AI workshop',
    imageCount: 28,
  },
  {
    id: '3',
    title: 'IEEE Day',
    category: 'Celebrations',
    imageUrl: 'https://picsum.photos/seed/11/400/300',
    imageHint: 'celebration event',
    imageCount: 52,
  },
  {
    id: '4',
    title: 'Industrial Visit',
    category: 'Tours',
    imageUrl: 'https://picsum.photos/seed/12/400/300',
    imageHint: 'industrial visit',
    imageCount: 34,
  },
  {
    id: '5',
    title: 'Guest Lectures',
    category: 'Seminars',
    imageUrl: 'https://picsum.photos/seed/13/400/300',
    imageHint: 'lecture hall',
    imageCount: 18,
  },
  {
    id: '6',
    title: 'Outreach Program',
    category: 'Social',
    imageUrl: 'https://picsum.photos/seed/14/400/300',
    imageHint: 'community outreach',
    imageCount: 22,
  },
];
