
import type { Event, TeamMember, GalleryAlbum } from './types';

export const mockEvents: Event[] = [
  {
    id: '13',
    title: 'IEEE Membership Drive',
    date: 'TBD',
    category: 'Recruitment',
    description: 'Join the IEEE Student Branch to be part of a vibrant community of innovators and leaders. Register now to get notified about our recruitment drive.',
    imageUrl: 'https://blog.interview-skills.co.uk/wp-content/uploads/2015/04/10-tips-for-interview-performance.jpg',
    imageHint: 'students team collaborating',
    status: 'upcoming',
    registrationLink: 'https://forms.gle/6UFqbdLw1uaoiYnv5',
  },
  {
    id: '1',
    title: 'INNOVISTA',
    date: '2025-10-08',
    category: 'Competition',
    description: 'A UI/UX design competition to challenge your creativity and design skills.',
    imageUrl: 'https://community.nasscom.in/sites/default/files/media/images/What%20is%20UIUX%20Transformation%20and%20How%20Does%20it%20Benefit%20Businesses-04_0.jpg',
    imageHint: 'UI UX competition design',
    status: 'upcoming',
    registrationLink: 'https://docs.google.com/forms/d/e/1FAIpQLSfk6ZvV5KSmKO0tjC0oJChfHfsNkN-lg9J-ojfehm6sb-RlMw/viewform?usp=header',
  },
  {
    id: '7',
    title: 'Hack the Gap',
    date: '2025-03-22',
    category: 'Competition',
    description: 'A hackathon focused on bridging the technology gap with innovative solutions.',
    imageUrl: 'https://drive.google.com/uc?export=view&id=1iE4NHtk3EFEWXFPTPwRm6nEcAgOUkNIT',
    imageHint: 'hackathon event',
    status: 'past',
  },
  {
    id: '8',
    title: 'Code A Thon',
    date: '2025-03-19',
    category: 'Competition',
    description: 'An intense coding marathon to challenge and showcase your programming skills.',
    imageUrl: 'https://drive.google.com/uc?export=view&id=1PaUtqWqDfoZdXzXNhWvIX7wiw7Ulvc4o',
    imageHint: 'coding marathon',
    status: 'past',
  },
  {
    id: '9',
    title: 'Py Quest',
    date: '2025-02-22',
    category: 'Competition',
    description: 'A quiz competition to test your knowledge of the Python programming language.',
    imageUrl: 'https://drive.google.com/uc?export=view&id=1G8jtgIA01N-GVtb7PhzQOHC16tICiV1p',
    imageHint: 'python quiz',
    status: 'past',
  },
  {
    id: '10',
    title: 'Crack Apti',
    date: '2025-02-26',
    category: 'Competition',
    description: 'An aptitude test to sharpen your problem-solving and logical reasoning skills.',
    imageUrl: 'https://media.licdn.com/dms/image/v2/D5612AQEB9ojqNMqdyQ/article-cover_image-shrink_600_2000/0/1683796312613?e=2147483647&v=beta&t=6_AHSUdISP6tBlYVT_aMeikM2Y7846IIxWOvmpLf3aw',
    imageHint: 'aptitude test',
    status: 'past',
  },
];

export const mockTeam: TeamMember[] = [
  {
    id: '1',
    name: 'Basvaraj Sirasgaonkar',
    role: 'Chairperson',
    bio: 'Leads the student branch with a vision for innovation and collaboration. Passionate about empowering students.',
    imageUrl: 'https://drive.google.com/uc?export=view&id=1FasmZTeY7WeeukvYlWOdzpIl1B3Gnb5t',
    imageHint: 'professional headshot',
    linkedin: '#',
  },
  {
    id: '2',
    name: 'Atharva Kulkarni',
    role: 'Vice Chairperson',
    bio: 'Assists in managing branch activities and focuses on strategic growth and member engagement.',
    imageUrl: 'https://drive.google.com/uc?export=view&id=1DtV3GCIcHD20LCACjQTvJk4yOTMKL1Qy',
    imageHint: 'professional headshot',
    linkedin: '#',
  },
  {
    id: '10',
    name: 'Palash Kale',
    role: 'Vice Chairperson',
    bio: 'Supports the chairperson and helps drive key initiatives within the student branch.',
    imageUrl: 'https://drive.google.com/uc?export=view&id=1c3bzgGmm5pNwZ2s4FnaMnWcDc9tYaVra',
    imageHint: 'professional headshot',
    linkedin: '#',
  },
  {
    id: '3',
    name: 'Aarya Padalkar',
    role: 'Secretary',
    bio: 'Manages all documentation, communications, and organizational tasks for the student branch.',
    imageUrl: 'https://drive.google.com/uc?export=view&id=1G8_0FIZObMTD8tY4hOvrqePiu7WHITIP',
    imageHint: 'professional headshot',
    linkedin: '#',
  },
  {
    id: '4',
    name: 'Syed Zaid',
    role: 'Treasurer',
    bio: 'Oversees the financial health of the branch, managing budgets for events and activities.',
    imageUrl: 'https://drive.google.com/uc?export=view&id=1ngkpF4vTAfelq8AE9LqYd9OrHN171-SQ',
    imageHint: 'professional headshot',
    linkedin: '#',
  },
  {
    id: '12',
    name: 'Swapnil Mane',
    role: 'Treasurer',
    bio: 'Manages financial records and ensures transparent and efficient use of branch funds.',
    imageUrl: 'https://drive.google.com/uc?export=view&id=1xO6g08iQ5HaXe35pVTcKErA7oWoWJBhT',
    imageHint: 'professional headshot',
    linkedin: '#',
  },
  {
    id: '13',
    name: 'Asjad Pathan',
    role: 'Technical Head',
    bio: 'Leads the technical committee, driving workshops and projects that build hands-on skills.',
    imageUrl: 'https://drive.google.com/uc?export=view&id=1YBVMkKiPc7csCyhnVc_8SrLRgCXKhgK1',
    imageHint: 'professional headshot',
    linkedin: '#',
  },
  {
    id: '14',
    name: 'Farooqui Furqan',
    role: 'Logistic Head',
    bio: 'Responsible for planning and coordinating the logistics for all branch events and activities.',
    imageUrl: 'https://drive.google.com/uc?export=view&id=1Sx9j_r99umdMDZsXFtkvbf1B91CJXIJr',
    imageHint: 'professional headshot',
    linkedin: '#',
  }
];

export const mockGallery: GalleryAlbum[] = [
  {
    id: '1',
    title: 'Hack the Gap',
    category: 'Hackathon',
    description: 'Our annual tech fest brought together students from across the university for a celebration of technology and innovation. This year\'s main event was the "Hack the Gap" hackathon.',
    imageUrl: 'https://drive.google.com/uc?export=view&id=1iE4NHtk3EFEWXFPTPwRm6nEcAgOUkNIT',
    imageHint: 'hackathon event',
    imageCount: 45,
  },
  {
    id: '2',
    title: 'AI Workshop',
    category: 'Workshops',
    description: 'A hands-on workshop where students learned the fundamentals of Artificial Intelligence and Machine Learning.',
    imageUrl: 'https://picsum.photos/seed/10/400/300',
    imageHint: 'AI workshop',
    imageCount: 28,
  },
  {
    id: '3',
    title: 'IEEE Day',
    category: 'Celebrations',
    description: 'Celebrating the global community of IEEE members and our shared passion for technology.',
    imageUrl: 'https://picsum.photos/seed/11/400/300',
    imageHint: 'celebration event',
    imageCount: 52,
  },
  {
    id: '4',
    title: 'Industrial Visit',
    category: 'Tours',
    description: 'A visit to a leading tech company, giving students a glimpse into the professional world of engineering.',
    imageUrl: 'https://picsum.photos/seed/12/400/300',
    imageHint: 'industrial visit',
    imageCount: 34,
  },
  {
    id: '5',
    title: 'Guest Lectures',
    category: 'Seminars',
    description: 'Industry experts shared their knowledge and experience on a variety of cutting-edge topics.',
    imageUrl: 'https://picsum.photos/seed/13/400/300',
    imageHint: 'lecture hall',
    imageCount: 18,
  },
  {
    id: '6',
    title: 'Outreach Program',
    category: 'Social',
    description: 'Engaging with the local community to promote STEM education and inspire the next generation of engineers.',
    imageUrl: 'https://picsum.photos/seed/14/400/300',
    imageHint: 'community outreach',
    imageCount: 22,
  },
];
